tunnel: ba3b9f92-f3c4-451d-9c86-80d2963cd145
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: nimbushomecloud.com
    service: http://client:80
  - service: http_status:404
